spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:webee}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  jwt:
    secret: ${JWT_SECRET_KEY:}
    access-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
    refresh-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:86400000}
    issuer: ${JWT_ISSUER:webee}