spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:webee}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          maxCompletionTokens: 1024

    vector-store:
      redis:
        uri: ${RAG_REDIS_URI:redis://localhost:6379}
        initialize-schema: true
        index: 'app-index'
        prefix: 'app:'

  servlet:
    multipart:
      max-file-size: 3MB

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

jwt:
  secret: ${JWT_SECRET_KEY:webee-temporary-secret-key}
  access-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:86400000}
  issuer: ${JWT_ISSUER:webee}

kakao:
  api-key: ${KAKAO_REST_API_KEY:}

was:
  api: ${WAS_API:http://localhost:8080}
  cors-allow-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_ACCESS_KEY:}
      region: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${AWS_S3_BUCKET:}
      cdn-url: ${AWS_CDN_URL:}

app:
  ai:
    max-messages: 5
    vector-store:
      topK: 5
      similarity-threshold: 0.75

    prompts:
      assistant-prompt: classpath:prompts/assistant/assistant-prompt.txt
      bee-recommendation-prompt: classpath:prompts/recommendation/bee_recommendation_prompt.txt
      bee-recommendation-query: classpath:prompts/recommendation/bee_recommendation_query.txt
      bee-disease-solution-query: classpath:prompts/disease/bee_disease_solution_query.txt
      bee-disease-solution-prompt: classpath:prompts/disease/bee_disease_solution_prompt.txt

bee:
  diagnosis:
    api-url: ${BEE_DIAGNOSIS_API_URL:http://localhost:5001/predict}
  recommendation:
    nongsaro:
      request-parameter-list: classpath:nongsaro-crop-pollination-request-parameter-list.csv

business-certificate-validation:
  api-key: ${BUSINESS_CERTIFICATE_API_KEY:}