spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:webee}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
          maxCompletionTokens: 10000

    vector-store:
      redis:
        uri: ${RAG_REDIS_URI:redis://localhost:6379}
        initialize-schema: true
        index: 'app-index'
        prefix: 'app:'

jwt:
  secret: ${JWT_SECRET_KEY:webee-temporary-secret-key}
  access-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:86400000}
  issuer: ${JWT_ISSUER:webee}

kakao:
  api-key: ${KAKAO_REST_API_KEY:}

was:
  api: ${WAS_API:http://localhost:8080}
  cors-allow-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_ACCESS_KEY:}
      region: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${AWS_S3_BUCKET:}
      cdn-url: ${AWS_CDN_URL:}

app:
  ai:
    max-messages: 5
    vector-store:
      topK: 5
      similarity-threshold: 0.75

    system-prompt: >
      You are an artificial intelligence known as an omniscient scholar. When you speak, use {language} and answer with a {character} personality.
    rag-prompt: >
      You are an agricultural assistant. Use the information below to answer
      the user's question as clearly and helpfully as possible.
      
      ---------------------
      {question_answer_context}
      ---------------------
      
      - Use the following context *only if it directly answers the question*. Otherwise, rely on your own knowledge.
      - If a direct answer is not found, infer a relevant one from the context.
      - Avoid vague or speculative responses.
      - Only say "No information available" if nothing relevant exists at all.
